name: messagepack
description: Streaming API implementation of MessagePack binary serialization format - msgpack.
version: 0.2.0
homepage: https://github.com/nailgilaziev/messagepack
repository: https://github.com/nailgilaziev/messagepack

environment:
  sdk: ">=2.12.0 <3.0.0"


dev_dependencies:
  test: ^1.16.0
